### ISSUE TITLE
can you add feature to make a telegram bot?

### ISSUE THREAD

**Issue by askfriends** [The-Antrax/heroku-buildpack-rclone-mod#2]
hi..

can you make a telegram bot which may do all the job for us, its easy and practical.

**Comment by The-Antrax** [comment]
@askfriends this is just a buildpack You are free to use it on any ShellBot,Userbot/Leechbot.

**Comment by askfriends** [comment]
> @askfriends this is just a buildpack You are free to use it on any ShellBot,Userbot/Leechbot.

Thanks for the reply..
im not pro in this regard, it would be nice if you could make it a telegram bot hosted on heroku to perform gclone operations. You can take help from some other available repos, it will take hardly half an hour to do that, but for me i dont have coding knowledge that much.

**Comment by The-Antrax** [comment]
You Can refer this [repo](https://github.com/smartass08/telegram_gcloner)
