### ISSUE TITLE
Is this using an rclone mod?

### ISSUE THREAD

**Issue by microtechton** [The-Antrax/heroku-buildpack-rclone-mod#3]
I don't seem to find any references to gclone your code other than the readme. It also seems that you reverted fclone changes too. Is this using an rclone mod or is it just normal rclone?

**Comment by The-Antrax** [comment]
It is Rclone Mod having rotating SAs feature of gclone. Yes Fclone commits reverted because Latest fclone run on "fclone copy" commands not on "rclone copy" that's why there was a separate buildpack of Fclone.
